### ISSUE TITLE
Turn Research into content for the Website

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/theory-of-online-misogyny#1]
**Objective**
Turn our research into content for our website

**Description**
We want to be transparent about our work, and thus display our research efforts on our website. 

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Research/define online misogyny for Opt Out Tools
- [ ] Turn into website content
- [ ] Think about next suitable content for website
