### ISSUE TITLE
Research Roadmap: Defining Online Misogyny for Opt Out

### ISSUE THREAD

**Issue by shepni** [opt-out-tools/theory-of-online-misogyny#12]
**Objective**
Arrive at a robust definition of online misogyny that all opt-out related work can draw on. 

**Description**
We need a robust, research-based definition of online misogyny that
* guides the code, data, activist, content, and research components of OO
* takes into account how different fields and actors have defined it for their own purposes
* allows us to communicate clearly, demarcate and justify what component(s) of online harassment OO addresses

**Skills**
Research
Feminist Theory

**Tasks**

- [x] Research EU/Intl. Organisations definitions of online misogyny (https://github.com/opt-out-tools/theory-of-online-misogyny/issues/5)
- [ ] Research Legal definitions of online misogyny (https://github.com/opt-out-tools/theory-of-online-misogyny/issues/19)
- [ ] Research Industry definitions of online misogyny (https://github.com/opt-out-tools/theory-of-online-misogyny/issues/16)
- [ ] Research Civil Society definitions of online misogyny (https://github.com/opt-out-tools/theory-of-online-misogyny/issues/18)
- [ ] Research academic definitions of online misogyny (https://github.com/opt-out-tools/theory-of-online-misogyny/issues/20)
- [ ] Identify additional fields/actors that have defined online misogyny and need to be researched (https://github.com/opt-out-tools/theory-of-online-misogyny/issues/6)
- [ ] Write a high-level definition of online misogyny that is based on the output of above research.
- [ ] [TBD] Break the definition down into x types of online misogyny that are relevant to OO
