### ISSUE TITLE
Feminist Principles of the Internet and Research and Application to OOT

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/theory-of-online-misogyny#7]
**Objective**
Research and discuss how to apply feminist principles of the internet

**Description**
The Feminist Principles of the Internet are a series of statements that offer a gender and sexual rights lens on critical internet-related rights. We want to research and embed these principles into Opt Out Tool's tech.

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [x] Create a Wiki entry on the FPIs
- [ ] Create a .md file on FPIs as guiding principles for Opt Out Tools
- [ ] Brainstorm/consult how to apply these into tech

**Comment by shepni** [comment]
Created Wiki entry about the FPIs (background info for those unfamiliar with them, excerpts of the most relevant ones for Opt Out Tools, links to further resources around the FPIs). See here https://github.com/opt-out-tools/theory-of-online-misogyny/wiki/Feminist-Principles-of-the-Internet
